LTG-35 - Write unit test for when a user creates password
alphagov/di-authentication-frontend pull request #41
Opened 2021-06-22 15:38 UTC by JHjava

## What?

- Write unit test for when a user creates password

## Why?

- So it is well tested

2021-06-22 16:23 UTC, dbes-gds commented on src/components/register-create-password/tests/register-create-password-controller.test.ts
> +      expect(next).to.have.been.calledOnce;
fixed

2021-06-23 10:20 UTC, sanisc requested changes

2021-06-23 10:20 UTC, sanisc commented on src/components/register-create-password/tests/register-create-password-controller.test.ts
> +    it("should throw invalid session error when session not populated", async () => {
this name of the test should probably be changed

2021-06-23 12:48 UTC, sanisc approved these changes

2021-06-23 12:49 UTC, merged